### ISSUE TITLE
duplicate uuid/volumeid

### ISSUE THREAD

**Issue by cubakcabak** [ArsenalRecon/Arsenal-Image-Mounter#1]
when mounting 2 or more disk image, the uuid of those volumename is conflicted/duplicated

(00000001-0000-0000-0000-000000000000)

its makes low level operations on the next after the first mounted drive failed, for example defragging it.

please make it so that the uuid for each mounted disk image randomly different, as if windows recognized it as other a physically mounted device drive.

**Comment by LTRData** [comment]
We will address this issue in a future update. It is a little bit difficult to find documentation about exactly how these volume id values are generated by upper-level drivers and what we could do at SCSI level to affect various pieces of them. But we have at least found a way to make them more unique than they are in the current version. It will need some more testing but will be published sooner or later.

**Comment by LTRData** [comment]
We hope that the uniqueness of Volume GUIDs are better in the latest version. We have added some additional identification from SCSI level that should be used in the calculations of Volume GUIDs. If anyone have more ideas and information about how to further improve this, we would really appreciate to hear about it!

Regards,
Olof Lagerkvist
