### ISSUE TITLE
Free ver of AIM do not mount splited vmdk, need DiscUtils/DIY something?

### ISSUE THREAD

**Issue by ccchan234** [ArsenalRecon/Arsenal-Image-Mounter#14]
hi.

i tried to use AIM to mount splited vmdk disk.

The install worked with splited raw,
but have "object reference not set to an instance of an object"error when i wanna mount a splited vmdk. 

the vmdk was created as shown in the picture, and is recognized
by virtualbox so should be valid.

I only have free ver and not sure free ver need DIY or manually build discutils for this?
I downloaded the zip file from https://arsenalrecon.com/downloads/,
named Arsenal-Image-Mounter-v3.1.101.zip

btw, 

As in the discussion elsewhere,
not all discutils support .vmdk size of larger than 20KB.
it would be nice if in later versions AIM could be modified
to handle the .vmdk of larger than 20KB. otherwise the total
vmdk disk will be limited to be 1TB.

thank you.

![Screenshot (7)](https://user-images.githubusercontent.com/37549409/78806591-754ab480-79f5-11ea-81bf-d0314fa09fa0.png)

**Comment by LTRData** [comment]
The fix for split vmdk images with large descriptor files that I made for DiscUtilsDevio (from another discussion) will be included in next version of AIM as well. I am not entirely sure that it is related to this particular error message though, I would have expected another error message. I'll check that!

**Comment by ccchan234** [comment]
my platform is win10, 64bit.

i read AIM need .net 4?

i am not sure my system comes with that,
if .net 4 need manually install?

thanks

**Comment by EricZimmerman** [comment]
windows 10 has everything you need already

**Comment by LTRData** [comment]
Just confirmed that I saw the same error in version .101 and this will be fixed in next version.

**Comment by ccchan234** [comment]
oh i saw the .107 version.

could mount splited vmdk now.

thank you.
