### ISSUE TITLE
LGPL license missing for redistribution of libewf

### ISSUE THREAD

**Issue by joachimmetz** [ArsenalRecon/Arsenal-Image-Mounter#19]
The LGPL license is missing for redistribution of libewf in https://github.com/ArsenalRecon/Arsenal-Image-Mounter/tree/master/libewf

Also likely missing are licenses for the Visual C++ Files https://docs.microsoft.com/en-us/cpp/windows/redistributing-visual-cpp-files?view=msvc-160

**Comment by joachimmetz** [comment]
And you likely want to add the license of zlib as well

**Comment by LTRData** [comment]
Thanks for noticing this. Added updated libewf.dll files with a license document.

**Comment by joachimmetz** [comment]
Thx for the quick changes, though I think that technically you still need to include a copy of the LGPL as well
Per https://www.gnu.org/licenses/gpl-faq.html#WhyMustIInclude 

```
Why does the GPL require including a copy of the GPL with every copy of the program? (#WhyMustIInclude)
Including a copy of the license with the work is vital so that everyone who gets a copy of the program can know what their rights are.

It might be tempting to include a URL that refers to the license, instead of the license itself. But you cannot be sure that the URL will still be valid, five years or ten years from now. Twenty years from now, URLs as we know them today may no longer exist.

The only way to make sure that people who have copies of the program will continue to be able to see the license, despite all the changes that will happen in the network, is to include a copy of the license in the program.
```

Which to my knowledge also applies to the AGPL of the main source

**Comment by LTRData** [comment]
Okay, I copied the LGPL license to a document called LICENSE in libewf directory, but maybe we should mention it in the license document for the whole repo as well. I also agree that we definitely should keep a copy of the full AGPL license in the repo as well. We will fix this! Thank you!

**Comment by joachimmetz** [comment]
That could work what I do for libewf itself have a copy of the LGPL and GPL (since the LGPL references the GPL license). Another common approach is to have a license directory with all the license information for the repo

**Comment by joachimmetz** [comment]
Can you also make sure to include the license in https://arsenalrecon.com/downloads/ and that of Dokan as well

**Comment by joachimmetz** [comment]
Can you also include a text file that indicate which version are used and what compiler was used to build them. It looks like you're using the bleeding edge development version in your zip file, which is **NOT** recommended.

**Comment by joachimmetz** [comment]
Ack and I see a copy of lgpl-3.0.txt, so that looks to me.

And it is transparent now, how and what is built. 

Thx

**Comment by LTRData** [comment]
All good then I think. Thank you for bringing this to our attention!
