### ISSUE TITLE
Mounting an image containing just a partition shows unpartitioned space

### ISSUE THREAD

**Issue by EricZimmerman** [ArsenalRecon/Arsenal-Image-Mounter#2]
hit me up if you need an example image

mounting an image of a physical disk works fine

**Comment by LTRData** [comment]
I have not tried this very much because it is not really what the driver is designed for. But I seem to recall that it usually works better if a single volume image is mounted as removable disk.

**Comment by EricZimmerman** [comment]
I can confirm selecting removable disk does in fact work just fine!
