### ISSUE TITLE
ArsenalImageMounterCLISetup.exe install old driver files

### ISSUE THREAD

**Issue by ohanaali** [ArsenalRecon/Arsenal-Image-Mounter#22]
ArsenalImageMounterCLISetup.exe install old driver files (from 2018) while ArsenalImageMounterGUISetup.exe install new driver files  from 2021

**Comment by LTRData** [comment]
Are you sure that you downloaded latest exe files from master branch?
https://github.com/ArsenalRecon/Arsenal-Image-Mounter/tree/master/DriverSetup

When I try it, I get the exact same driver files installed by both application files.

**Comment by john-8998** [comment]
I see the problem:
The drivers files are indeed the latest, it's just that those in the ArsenalImageMounterXXXSetup.exe are dated to 2018-04-25 (that's also true for the "DriverFiles.zip" file.

"DriverSetup.7z" is the only one with the correct file timestamps.

> Are you sure that you downloaded latest exe files from master branch? https://github.com/ArsenalRecon/Arsenal-Image-Mounter/tree/master/DriverSetup
> 
> When I try it, I get the exact same driver files installed by both application files.

**Comment by LTRData** [comment]
Ah, yes that is right. There is something strange with timestamps on files in zip archives that have been updated with .NET zip archive features (System.IO.Compression.ZipArchive etc). Timestamps are updated when looking at the zip archive from that API but not from most other zip tools. In future versions the embedded setup packages will be extracted using this .NET API as well and then timestamps will be correct.
