### ISSUE TITLE
A property file seems to be missing from the repo, aim_um.props.

### ISSUE THREAD

**Issue by KaoDome** [ArsenalRecon/Arsenal-Image-Mounter#25]
Hi, out of curiosity I checked out the source to have a better look at it and all, I'm way over my head here, but I figured it wouldn't hurt to see how pros do things and hopefully learn something in the process.

When opening the unmanaged source solution, ArsenalImageMounter.sln, Visual Studio complained about a couple of missing things, the WDK for starters and then some prop files that come from a previous product it seems, ImDisk. I located it and installed the required toolchains. Since the environment was already the current preview of VS2022 I settled for the latest WDK too (Windows 11 22H2's).

However, one prop file seems to be missing from the repo and I can't seem to be able to locate it, it is `Arsenal-Image-Mounter\Unmanaged Source\aim_um.props` required by at least `aim_ll`, `aimapi` and `aimwrfltr`. Was it a mishap? I didn't see it listed in the `.gitignore` file though.

Thanks for everything!

PS. _There seems to be another one missing too, `Arsenal-Image-Mounter\Unmanaged Source\aimwrfltr\aimwrfltr.props`_

**Comment by LTRData** [comment]
...and fixed the other missing props file too now.
