### ISSUE TITLE
VHDX Dynamic Memory Management

### ISSUE THREAD

**Issue by lollita** [ArsenalRecon/Arsenal-Image-Mounter#30]
Do it not possible to create a dynamically expanding VHDX image?

**Comment by LTRData** [comment]
It will be possible in the next release. It uses updated versions of DiscUtils libraries where this has been implemented.

**Comment by LTRData** [comment]
Or you meant dynamically allocated RAM disk with a vhdx as template? No, that is not supported. It would require level level support for vhdx that we do not have.
