### ISSUE TITLE
BitLocker password prompting 

### ISSUE THREAD

**Issue by lollita** [ArsenalRecon/Arsenal-Image-Mounter#34]
Do it have a command line to mount a BitLocker vhdx prompting for password as gui do without notification?
Do ti have a WinApi also to get it.

**Comment by LTRData** [comment]
Yes, there is a WMI API for Bitlocker that you can use also with AIM mounted images. Otherwise, to simply show the Bitlocker unlock GUI dialog, you can start bdeunlock.exe (in system32 directory) with drive letter as parameter.

**Comment by lollita** [comment]
I found UnlockWithPassphrase WMI but a command prompt as BdeUnLock.exe.
Do it esist?

**Comment by LTRData** [comment]
Yes,
`manage-bde -unlock D: -pw`

**Comment by lollita** [comment]
Ty, i know but I mean WMI query to prompt with a Windows InputBox as BdeUnLock.exe, not dos bos as manage-bde.

**Comment by LTRData** [comment]
Ah, no WMI does not show dialog boxes in that way. It is intended for non-interactive use. If you want a GUI password prompt, use bdeunlock.exe.
