### ISSUE TITLE
Force ImScsiRemoveDeviceByMountPoint

### ISSUE THREAD

**Issue by lollita** [ArsenalRecon/Arsenal-Image-Mounter#36]
Do it is possible to use Force parameter when use ImScsiRemoveDeviceByMountPoint API?
I have to use
ImScsiSetAPIFlags(IMSCSI_API_FORCE_DISMOUNT);
before?

**Comment by LTRData** [comment]
No, the only way to force dismount is to set flag to force dismounts with `ImScsiSetAPIFlags`.
