### ISSUE TITLE
Cannot access Arsenal Image Mounter driver

### ISSUE THREAD

**Issue by PowerBinn** [ArsenalRecon/Arsenal-Image-Mounter#37]
i use aim_cli .exe -version3.9.239
Cmd line like this"aim_cli --mount --filename=D:\USB\Virtualusb.E01"
but return"Cannot access Arsenal Image Mounter driver. Check that the driver is installed and that you are running this application with administrative privileges.

No Arsenal Image Mounter adapter found."

**Comment by LTRData** [comment]
You need to install the driver first. You can either do that by starting the GUI application once first, or by running `aim_ll.exe` tool with `--install` switch.

**Comment by PowerBinn** [comment]
I have tried starting the GUI application,it still displays the same issue.

**Comment by LTRData** [comment]
Does it work in the GUI application? What happens if you try to mount the image file there?

**Comment by PowerBinn** [comment]
I can mount disk image file successfully by using GUI application.

**Comment by LTRData** [comment]
That sounds strange. Are you really sure that the command prompt where you try the command line version is running with administrative (elevated) privileges?

**Comment by PowerBinn** [comment]
Thank you very much! I have finally solved this problem. My problem lies in not running cmd with administrator privileges
