### ISSUE TITLE
RAMDisk - only half of the allocated memory can be used

### ISSUE THREAD

**Issue by Whatslp** [ArsenalRecon/Arsenal-Image-Mounter#38]
Same with ImDisk only half of the allocated memory usable.
When i copy files to the RAM-Drive (within WinPE Projects Winbuilder/PhoenixPE). Every file uses at least twice the size it actually has on the RAMDrive. If i allocate 2 GB - i can barely use 1 GB. The size of the files is correct on the drive.

**Comment by LTRData** [comment]
I just tried both fixed allocated 2 GB RAM disk and also tried dynamically allocated 2 GB RAM disk (AWE allocation, from VHD template). In both cases I could write an almost 2 GB large file to the virtual disk without issues. I have not used Winbuilder for many years so I do not really know how these features are used there.
