### ISSUE TITLE
aim_ll & the format prompt

### ISSUE THREAD

**Issue by xesarni** [ArsenalRecon/Arsenal-Image-Mounter#39]
aim_ll triggers the format prompt "You need to format the disk in drive E: before you can use it. Do you want to format it?". In my case, E: is the first unused drive.

Command used:
aim_ll.exe -a -s 2048M -m R: -p "/fs:ntfs /q /y /v:RAM"

Is there any way to get rid of that prompt?

Windows 10 22H2 x64, latest AIM & aim_ll

**Comment by LTRData** [comment]
The only way that I am aware of is to disable automatic drive letter assignments globally in Windows.
`mountvol /n`

But the downside of that is that you will no longer have drive letters assigned for any other kind of drive you attach either, not for USB drives etc.

**Comment by xesarni** [comment]
That's good enough for me. Thanks!
