### ISSUE TITLE
Extra commands for aimll.exe

### ISSUE THREAD

**Issue by Virgus** [ArsenalRecon/Arsenal-Image-Mounter#4]
Hello,
I've been testing aimll.exe for a while and it's a great tool!
I'd like to thank you and ask if there exists a command to unmount every existing mount (like "remove all" in ArsenalImageMounterMountTool.exe).

Thanks and have a nice weekend.
V.

**Comment by LTRData** [comment]
Hello,
Thanks for your kind words! We are glad you found it useful!

You can remove all mounted virtual disks using the -d switch alone and not specify a particular device number to remove:
aim_ll -d

Have a nice weekend.
// Olof Lagerkvist

**Comment by Virgus** [comment]
Great, many thanks Olof!
