### ISSUE TITLE
Is it possible to change the properties of a mounted disk?

### ISSUE THREAD

**Issue by adlemx** [ArsenalRecon/Arsenal-Image-Mounter#49]
Is it possible to change the serial number and model (same as device name) of the disk that is mounted using AIM?
Currently the disk model is listed as Arsenal Virtual SCSI Disk Device, and the s/n is a random uuid

**Comment by LTRData** [comment]
No, sorry, the logic for this is hard coded in the driver.

**Comment by adlemx** [comment]
Are you talking about phdskmnt.sys? What if I change it in the sources and compile it manually?

**Comment by LTRData** [comment]
Yes that's right. I think it should be fairly easy to make that change. There is a code path that is used to generate a unique id here: 
https://github.com/ArsenalRecon/Arsenal-Image-Mounter/blob/7e0fd50ffff13a6da1691e6dc60241e3b690083e/Unmanaged%20Source/phdskmnt/iodisp.cpp#L2235

**Comment by adlemx** [comment]
Thanks, I found this line of code, but it seems like the disk name should be the same as the image name, but it's not. 
https://github.com/ArsenalRecon/Arsenal-Image-Mounter/blob/7e0fd50ffff13a6da1691e6dc60241e3b690083e/Unmanaged%20Source/phdskmnt/iodisp.cpp#L2155
I also tried searching for "Arsenal Virtual SCSI Disk Device" throughout the solution, but I couldn't find anything. Can you please tell me where the device name is set?

**Comment by LTRData** [comment]
> Thanks, I found this line of code, but it seems like the disk name should be the same as the image name, but it's not. 
> https://github.com/ArsenalRecon/Arsenal-Image-Mounter/blob/7e0fd50ffff13a6da1691e6dc60241e3b690083e/Unmanaged%20Source/phdskmnt/iodisp.cpp#L2155

"File name" in this context is not related to the image file name if the actual image file is opened and handled by a user mode library. In such cases, the driver had no knowledge of the image file and this file name is rather the "file" used for communication between kernel level driver and the user mode backend.

> I also tried searching for "Arsenal Virtual SCSI Disk Device" throughout the solution, but I couldn't find anything. Can you please tell me where the device name is set? 

Those strings are defined here: 
https://github.com/ArsenalRecon/Arsenal-Image-Mounter/blob/7e0fd50ffff13a6da1691e6dc60241e3b690083e/Unmanaged%20Source/phdskmnt/inc/phdskmnt.h#L94

**Comment by adlemx** [comment]
> Those strings are defined here:
> 
> https://github.com/ArsenalRecon/Arsenal-Image-Mounter/blob/7e0fd50ffff13a6da1691e6dc60241e3b690083e/Unmanaged%20Source/phdskmnt/inc/phdskmnt.h#L94

Thanks, but in this file I found only symbols "Arsenal" and "Virtual", although I can find other symbols: "SCSI", "Disk" and "Device"

**Comment by LTRData** [comment]
The string "SCSI Disk Device" must be from somewhere else. Where did you see that? What application showed that string? It is likely just a description of a device class or something like that.

**Comment by LTRData** [comment]
As for the build, you need to have WDK for Windows 10 installed and then in project properties point it to use the same WDK build toolchain as you have installed.

**Comment by adlemx** [comment]
> The string "SCSI Disk Device" must be from somewhere else. Where did you see that? What application showed that string? It is likely just a description of a device class or something like that.

It shows up in the wmik and in the device manager.
![image](https://github.com/user-attachments/assets/39cf7f15-91cc-420a-a092-faca0ece0995)

I need the full model name of the drive to be equal to WDC WD40EZRZ-75GXCB0, is this possible?

**Comment by LTRData** [comment]
You would need a completely different kind of driver for that. A SCSI miniport like AIM would not be sufficient to control in detail what kind of device you create in that way. You can only chose between some SCSI device types and "SCSI Disk Device" is the only one that will emulate a disk.

You see the same behavior for the device below it, the ITGZ NvME that most probably also uses a simple SCSI miniport driver to emulate a SCSI disk using an NvME memory card. It also shows as a "SCSI Disk Device", because that is essentially what it is to the operating system.

**Comment by LTRData** [comment]
You can use my `devioctl` tool at https://ltr-data.se/files/win64/devioctl64.zip to see the properties that a disk driver actually returns for a disk.

For example:
`devioctl storprop C:`
or something like:
`devioctl storprop physicaldrive1`

**Comment by adlemx** [comment]
![image](https://github.com/user-attachments/assets/0c6c9fb1-c054-48a6-9d34-989e67c53b94)
Yes, thanks, I understand. Is there any other virtual device driver in which you can completely change the model and s/n?

**Comment by LTRData** [comment]
I am not sure but I imagine there are probably not that many available. To for example emulate SATA instead of SCSI Disk also means a bit different behavior in various ways, so it is not as simple as just changing a device type flag or similar.

**Comment by adlemx** [comment]
Can you please name at least one project that can emulate sata? I tried searching but couldn't find a single one

**Comment by LTRData** [comment]
No, I do not know of any myself. Also, it seems it could be very difficult to implement it as a SATA miniport driver because of lack of the concept of "virtual miniport" for SATA port driver as opposed to Storport port driver (for SCSI). So, you might need to create a complete port driver yourself with the device properties you want.
