### ISSUE TITLE
Can not build on VS2022

### ISSUE THREAD

**Issue by Antecer** [ArsenalRecon/Arsenal-Image-Mounter#50]
![image](https://github.com/user-attachments/assets/4bfe2ce1-90c7-4b99-af41-b026e43252f9)

ArsenalImageMounterHelpBuilder\ArsenalImageMounterHelpBuilder.shfbproj: 找不到此项目类型所基于的应用程序。

**Comment by LTRData** [comment]
That is the project that builds the API documentation. You could either skip this project in your build, or install Sandcastle to get the components needed to build the documentation.

**Comment by Antecer** [comment]
![image](https://github.com/user-attachments/assets/c59ec474-9874-46d7-a253-377c064a8658)

I get this error: Stream not includes GetPositionInBaseStream

**Comment by LTRData** [comment]
Thanks for reporting this.

I'll check that latest DiscUtils libraries are pushed to Nuget.

**Comment by LTRData** [comment]
> I get this error: Stream not includes GetPositionInBaseStream

Fixed by https://github.com/ArsenalRecon/Arsenal-Image-Mounter/commit/a0bfec4509304a1357fb5dd61258ff0b8a4ce8a6
