### ISSUE TITLE
Multi part image last sector error

### ISSUE THREAD

**Issue by YahavR** [ArsenalRecon/Arsenal-Image-Mounter#6]
When mounting a multi part raw image (dump) and reading from a physical last sector it throws an error code 1117, Device I/O error.

To reproduce:
1. Create spli disk dump or split a raw image into multiple parts.
2. Mount (with multi part provider)
3. Open physical drive (CreateFile \\?\PhysicalDrive)
4. Seek to the last sector (end of the disk minus sector size)
5. Read 1 sector

Notes:
1. This happens only with multi part provider, I have mounted and successfully read the same sector of nonsplit image.
2. The last sector that doesn't serve the operation system and found by calculating the geometry of the drive or the sum of the size of all image parts.
3. This works on other mounters.
4. Arsenal process called ReadFile with correct parameters - the correct part and offset.

**Comment by LTRData** [comment]
Thanks for reporting, I'll check this!

**Comment by LTRData** [comment]
Verified and fixed. Fix will be included in next release.
