### ISSUE TITLE
Graphical user interface application is not available

### ISSUE THREAD

**Issue by johnd0e** [ArsenalRecon/Arsenal-Image-Mounter#9]
https://github.com/ArsenalRecon/Arsenal-Image-Mounter/blob/d0b3d5bf228789f37770ab1c14910d6b3fcae8e1/Graphical%20applications/Graphical%20application%20moved.txt#L1-L4
[Link](https://arsenalrecon.com/weapons/image-mounter/) is broken.

**Comment by JonnyTech** [comment]
@ArsenalRecon is there an alternative link?

**Comment by ArsenalSpencer** [comment]
It is now much easier to download the latest GUI version of Arsenal Image Mounter... go to the Downloads section of our website at:

https://ArsenalRecon.com/downloads/

No mailing list registration needed.
